export const words = [
  "Lisk",
  "LiskL2",
  "Ethereum",
  "Optimism",
  "Superchain",
  "BootCamp",
  "Blockchain",
  "Incubation",
  "Africa",
  "Startups",
  "Tokenomics",
  "PitchDeck",
  "MVP",
  "GoToMarket",
  "Mentorship",
  "Funding",
  "Grant",
  "BuilderGrant",
  "BoosterGrant",
  "Interoperability",
  "Scalability",
  "LiskSDK",
  "LiskCodec",
  "DPoS",
  "Web3",
  "Decentralized",
  "Developers",
  "Hackathon",
  "DemoDay",
  "CVLabs",
  "KEYDifferenceLabs",
  "Accubits",
  "MarketAcross",
  "Aquapurge",
  "Jamit",
  "PropOut",
  "LiskBuildersClub",
  "GDG",
  "Zoom",
  "Discord",
  "Pitching",
  "Storytelling",
  "TokenUtility",
  "Community",
  "Ecosystem",
  "Education",
  "Workshops",
] as const;

export const ABI = [
  {
    inputs: [],
    name: "lastWithdrawalTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
